### ISSUE TITLE
Make sure all results are well zipped

### ISSUE THREAD

**Issue by ehoelzl** [mlbench/mlbench-dashboard#44]
Sometimes, it occurs that some results are not in the zip file (in a random way). We should look into it as to avoid having to re-run the same tasks multiple times

**Comment by Panaetius** [comment]
Do the metrics themselves exist on the server? or is this just a symptom of missing metrics?

**Comment by ehoelzl** [comment]
Well, they are displayed in the dashboard. Its usually the `global` metrics that are missing, not sure why

**Comment by Panaetius** [comment]
That's weird
